### ISSUE TITLE
basic continuous integration

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/work-api#6]
Since we have code that will be merged soon, we should set up some very basic CI on this repo:

- go build
- gofmt
- unit tests (when applicable)
- e2e (when applicable)

For e2e i imagine we can get quite a ways on github actions and KIND

**Comment by RainbowMango** [comment]
@pmorie could you help confirm does the `Actions` enabled for this repo?

**Comment by RainbowMango** [comment]
also cc @nikhita , if you have time :)

**Comment by nikhita** [comment]
> also cc @nikhita , if you have time :)

@RainbowMango :wave: Actions is enabled. Here is a screenshot :)


![Screenshot from 2021-03-18 14-37-13](https://user-images.githubusercontent.com/16105680/111600461-72f0fd00-87f7-11eb-895d-79984df0a087.png)

**Comment by RainbowMango** [comment]
Thanks @nikhita !!!
